name: backEnd server CD
on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  server-cd:
    runs-on: ubuntu-latest
    steps:
      - name: âœ… ì½”ë“œ ì²´í¬ì•„ì›ƒ
        uses: actions/checkout@v3

      - name: ðŸ‘» ë…¸ë“œ ì„¤ì •
        uses: actions/setup-node@v3
        with:
          node-version: "21"

      - name: ðŸƒâ€â™‚ï¸ Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USER}}
          key: ${{secrets.PEM_KEY}}
          port: ${{secrets.PORT}}
          script: |
            cd /home/ubuntu/WhereMyBus-BE/server
            echo "${{secrets.ENV}}" > .env.prod
            echo "${{secrets.FIREBASE}}" > firebase-adminsdk.json
            git pull origin main
            npm ci -y
            npm run build
            pm2 reload ecosystem.config.js
            
