name: backEnd server CI
on:
  pull_request:
    branches: [dev, main]

permissions:
  contents: read

jobs:
  server-ci:
    runs-on: ubuntu-latest
    steps:
      - name: âœ… ì½”ë“œ ì²´í¬ì•„ì›ƒ
        uses: actions/checkout@v3

      - name: ğŸ‘» ë…¸ë“œ ì„¤ì •
        uses: actions/setup-node@v3
        with:
          node-version: "21"

      - name: â¬‡ï¸ ì˜ì¡´ì„± ì„¤ì¹˜
        working-directory: ./server
        run: npm ci -y

      - name: ğŸ“¦ í”„ë¡œì íŠ¸ ë¹Œë“œ
        working-directory: ./server
        run: npm run build

#      - name: ğŸ”‘ ENV íŒŒì¼ ìƒì„±
#        working-directory: ./server
#        run: |
#          echo "${{secrets.ENV_TEST}}" > .env.dev
#          echo "${{secrets.ENV}}" > .env.prod
#          echo "${{secrets.FIREBASE}}" > firebase-adminsdk.json
#          pwd
#          ls -al
#
#      - name: âœ… ìœ ë‹› í…ŒìŠ¤íŠ¸
#        working-directory: ./server
#        run: npm test
